services:
  postgres:
    container_name: postgres
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped

  cassandra:
    container_name: cassandra
    image: cassandra:latest
    volumes:
      - cassandra_data:/var/lib/cassandra
    env_file:
      - .env
    ports:
      - "9042:9042"
    restart: unless-stopped

volumes:
  cassandra_data
  postgres_data